### ISSUE TITLE
Getting error 'Uncaught ReferenceError: window is not defined in bootstarp'

### ISSUE THREAD

**Issue by UmeshRajani** [patidar-suresh/angular-cli6-webworker#1]
Hello Suresh,

I'm getting this error:

Uncaught ReferenceError: window is not defined in bootstarp: 123
var jsonpArray = window["webpackJsonp"] = window["webpackJsonp"] || [];
I tried this web worker example plainly and getting this issue , am I missing anything? 
Please help me.

**Comment by patidar-suresh** [comment]
Hi Umesh,
I just tried running this code again and it seems to be working fine for me. Here is what I did:
1. Cloned the repository in a new directory.
2. Run "npm install" from checked out directory.
3. Run "ng serve" and accessed application from browser (http://localhost:4200)

It worked as expected for me, without any error in application or console.
Here is my dev environment:
`Angular CLI: 6.1.5,
Node: 8.9.3,
Angular: 6.1.7,
OS: win32 x64`

Could you please let me know your development environment? You can get it by running command `ng -version` from project directory.

**Comment by glmanhtu** [comment]
I have got the same issue. Here is my specs:

Angular CLI: 7.0.5
Node: 10.6.0
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.10.5
@angular-devkit/core         7.0.5
@angular-devkit/schematics   7.0.5
@schematics/angular          7.0.5
@schematics/update           0.10.5
rxjs                         6.3.3
typescript                   3.1.6

I think, something happened with the libraries. For any reason, it doesn't work anymore

**Comment by patidar-suresh** [comment]
There are significant changes between Angular 6 and Angular 7 (in both library and cli). So it is quite possible that this example code might  not work for Angular 7.

The example is created for Angular 6 with CLI 6 and it works perfectly fine with it.
To work with Angular 7 the code might need some changes. I will create another repository for example code  written for Angular 7 and CLI 7

**Comment by Standaa** [comment]
Same error here, app does not work despite the config being :
Angular CLI: 6.1.5
Node: 11.6.0
OS: darwin x64
Angular: 6.1.7
